# Generated by Django 4.0.5 on 2022-06-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'ordering': ['issuer', 'name'],
            },
        ),
    ]
